### ISSUE TITLE
Which components the temperature sensors refer to

### ISSUE THREAD

**Issue by haltlos** [andreafabrizi/G4FanControl#1]
Hello Andrea, I am delighted to have found G4FanControl. After replacing the original Hitachi HDD in my PowerBook G4 notebook (12-inch PowerBook6,8 with one fan) with a [OWC SSD](https://eshop.macsales.com/item/OWC/SSDMLP120/), I got interested in observing temperatures and controlling fan speed.

The temperature measurements of sensors 1, 2 and 3 would be more informative if it were know which components they refer to. To find out, I compared the temperature values by the iStat pro Dashboard widget to those of G4FanControl. They do correspond to each other. The screenshot shows both applications next to each other.

![temperature comparison](https://user-images.githubusercontent.com/4324234/40029512-40f01d6c-57e5-11e8-8196-9e3b2b68f9f9.png)

From that I conclude that 
- sensor 1 measures hard drive temperature
- sensor 2 measures CPU
- sensor 3 measures GPU

I would like to know where this image is taken from - which software was used to track the temperatures?

![image](https://user-images.githubusercontent.com/4324234/40029613-d4443a30-57e5-11e8-88a9-4fe41a6fdbd5.png)
Image source: [https://www.andreafabrizi.it/2007/06/11/G4FanControl/](https://www.andreafabrizi.it/2007/06/11/G4FanControl/)

**Comment by andreafabrizi** [comment]
Hi @haltlos, thanks for sharing your findings! Unfortunately I took that screenshot like 10 years ago and I absolutely don't remember which tool I used... sorry!

**Comment by haltlos** [comment]
It may have been Temperature Monitor, which was replaced by [Hardware Monitor](http://www.bresink.com/osx/HardwareMonitor.html).
